# Generated by Django 4.2.11 on 2024-05-01 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_id', models.IntegerField()),
                ('owner', models.CharField(max_length=30)),
                ('property_type', models.CharField(max_length=50)),
                ('offer_type', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('contact_ph', models.CharField(max_length=15)),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime(2024, 5, 1, 7, 56, 29, 821757))),
            ],
        ),
    ]
